services:
  - type: web
    name: nsac-campus-companions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: nsac-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
databases:
  - name: nsac-db
    databaseName: nsac
    user: nsac_user
